#let abbreviations = (
  (abb: "NFR", desc: "Non-Functional Requirements"),
  (abb: "AI", desc: "Artificial Intelligence, especially LLM"),
  (abb: "LLM", desc: "Large Language Model"),
  (abb: "REST", desc: "Representational State Transfer"),
  (abb: "API", desc: "Application Programming Interface"),
  (abb: "UI", desc: "User Interface"),
  (abb: "UT", desc: "Unit Testing"),
  (abb: "TMP", desc: "Template Metaprogramming"),
  (abb: "GTest", desc: "Google Test"),
  (abb: "SFINAE", desc: "Substitution Failure Is Not An Error"),
  (abb: "GCC", desc: "GNU Compiler Collection"),
  (abb: "GNU", desc: "Recursive Acronym for \"GNU's Not Unix!\""),
  (abb: "TD", desc: "Template Declarations"),
  (abb: "RTT", desc: "Round-Trip Time"),
)
