name: CPPChecker

services:
  backend:
    container_name: cxxchecker_server
    build:
      context: .
      dockerfile: src/Dockerfile
    deploy:
      resources:
        limits:
          cpus: "4.00"
          memory: 1200M
        reservations:
          cpus: "0.50"
          memory: 150M
    privileged: true
    volumes:
      - ./archive:/app/archive
    ports:
      - "8008:8008"
    restart: unless-stopped
    healthcheck:
      disable: false
      test: ["CMD", "curl", "-f", "http://localhost:8008/healthcheck"]
      interval: 60s
      timeout: 10s
      retries: 3
    networks:
      - cxxchecker-data

  frontend:
    container_name: vue
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    restart: unless-stopped
    networks:
      - cxxchecker-data
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_started

networks:
  cxxchecker-data:
