name: CPPChecker

services:
  backend:
    container_name: cxxchecker_server
    build:
      context: .
      dockerfile: src/Dockerfile
    deploy:
      resources:
        limits:
          cpus: "4.00"
          memory: 1200M
        reservations:
          cpus: "0.50"
          memory: 150M
    privileged: true
    volumes:
      - ./archive:/app/archive
      - ./temp:/app/temp
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      disable: false
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 60s
      timeout: 10s
      retries: 3
    networks:
      - cxxchecker-data

networks:
  cxxchecker-data:
