.PHONY: watch

default: watch

watch:
	typst watch thesis.typ


help:
	@echo "Available targets: "
	@echo "  make 	- Incrementally recompile thesis.typ"
	@echo "  make watch   - Incrementally recompile thesis.typ"