name: Build and release thesis

on:
  push:
    branches:
      - main
    paths:
      - "thesis/**"

permissions:
  contents: write

jobs:
  build_release_thesis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: "0"
          lfs: true

      - name: Cache Fonts
        id: cache-fonts
        uses: actions/cache@v5
        with:
          path: ~/.local/share/fonts
          key: fonts-with-CJK2-${{ runner.os }}
          restore-keys: |
            fonts-with-CJK2-

      - name: Install Fonts (if not cached)
        if: steps.cache-fonts.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.local/share/fonts

          wget -O /tmp/newcomputermodern.zip "https://fontesk.com/download/39191"
          unzip -o /tmp/newcomputermodern.zip -d /tmp/newcomputermodern/
          cp /tmp/newcomputermodern/*.otf ~/.local/share/fonts/

          wget -O /tmp/NotoSansCJKsc-Thin.otf "https://github.com/googlefonts/noto-cjk/raw/main/Sans/OTF/SimplifiedChinese/NotoSansCJKsc-Thin.otf"
          cp /tmp/NotoSansCJKsc-Thin.otf ~/.local/share/fonts/

          # Refresh font cache
          fc-cache -f -v

      - name: Create initial tag
        run: |
          if [ -z "$(git tag -l 'v*')" ]; then
            git tag v0.0.0
          fi

      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: "patch"

      - uses: typst-community/setup-typst@v4

      - name: Compile Thesis
        run: typst compile thesis/thesis.typ thesis.pdf

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          name: Version ${{ steps.bump.outputs.new_tag }}
          draft: false
          prerelease: false
          files: |
            thesis.pdf
