name: Catch2 Headerfile Test

on:
  push:
    branches:
      - main
    paths:
      - 'CPPChecker/As_header/**'
  pull_request:
    branches:
      - main
    paths:
      - 'CPPChecker/As_header/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install g++
        run: sudo apt-get install -y g++

      - name: Compile catch_main.cpp with g++ (C++20)
        run: |
          g++ -std=c++20 -o catch_main CPPChecker/As_header/Catch2_Tests/catch_main.cpp
        working-directory: ${{ github.workspace }}

      - name: Run catch_main.cpp
        run: |
          ./catch_main
        working-directory: ${{ github.workspace }}
        id: catch_output

      - name: Display catch_main.cpp output
        run: echo "Output from catch_main.cpp: ${{ steps.catch_output.outputs.stdout }}"


