name: Run Catch2 Tests on test.cpp

on:
  push:
    branches:
      - main
    paths:
      - 'CPPChecker/As_header/**'
  pull_request:
    branches:
      - main
    paths:
      - 'CPPChecker/As_header/**' 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install g++
        run: sudo apt-get install -y g++

      - name: Compile C++ files with g++ (C++20)
        run: |
          for file in CPPChecker/As_header/Catch2_Tests/*.cpp
          do
            g++ -std=c++20 -o "${file%.cpp}" "$file"
          done
        working-directory: ${{ github.workspace }}

