name: Catch2 Headerfile Test

on:
  push:
    branches:
      - main
    paths:
      - 'CPPChecker/As_header/**'
  pull_request:
    branches:
      - main
    paths:
      - 'CPPChecker/As_header/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install g++
        run: sudo apt-get install -y g++

      - name: Compile and run catch_main.cpp with g++ (C++20)
        run: |
          g++ -std=c++20 -o catch_main CPPChecker/As_header/Catch2_Tests/catch_main.cpp
          ./catch_main
        working-directory: ${{ github.workspace }}
        continue-on-error: true  # Continue even if the tests fail

 



